import Footer from "./Components/Footer";
import "./globals.css";

export const metadata = {
  title: "Homezen Trading and Construction",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}


